- id: '1010'
  alias: Notifica avvio di Hassio
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.notify
    data:
      message: Hassio avviato con ip esterno {{ state_attr('sensor.fritz_netmonitor', 'external_ip') }}
      
- id: '3000'
  alias: Accendi TVCC e attiva motion detection quando non rimane nessuno
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  action:
  - service: notify.notify
    data_template:
      message: 'Attivo motion detection'
  - service: input_boolean.turn_on
    entity_id: input_boolean.m5cam_motion_detection
  - service: input_boolean.turn_on
    entity_id: input_boolean.soggiorno_motion_detection
  - service: switch.turn_on
    entity_id: switch.smart_usb_relay_2

- id: '3500'
  alias: 'Notifica quando vengono accese luci con nessuno in casa'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.all_lights
    to: 'on'
  condition:
  - condition: state
    entity_id: group.people
    state: 'not_home'
  action:
  - service: notify.notify
    data_template:
      message: 'Lights ON with everyone outside!'
      
- id: '3510'
  alias: 'Notifica luci accese quando non rimane nessuno'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.people
    from: 'home'
    to: 'not_home'
  condition:
  - condition: state
    entity_id: group.all_lights
    state: 'on'
  action:
  - service: notify.notify
    data_template:
      message: 'You left with lights ON!'
      
- id: '4000'
  alias: Spegni TVCC e motion detection quando rientra qualcuno
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.people
    from: 'not_home'
    to: 'home'
  action:
  - service: notify.notify
    data_template:
      message: 'Disattivo motion detection'
  - service: input_boolean.turn_off
    entity_id: input_boolean.m5cam_motion_detection
  - service: input_boolean.turn_off
    entity_id: input_boolean.soggiorno_motion_detection
  - service: switch.turn_off
    entity_id: switch.smart_usb_relay_2

- id: '7020'
  alias: Notifica rilevazione movimento m5cam
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.m5cam_pir
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.m5cam_motion_detection
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: Motion detection (m5cam)
  - service: script.notify_camera
    data:
      entity_id: camera.m5cam
    
- id: '7030'
  alias: Notifica rilevazione movimento soggiorno
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.m5stickc_pir_hat_pir
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.soggiorno_motion_detection
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: Motion detection (soggiorno)
  - service: script.notify_camera
    data:
      entity_id: camera.hikam_s5
    
- id: '9000'
  alias: 'Telegram start'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
  - service: notify.notify
    data:
      message: 'commands'
      data:
        keyboard:
          - '/cam 1, /cam 2, /cam 3, /cam 4'
          - '/lights_off, /lights_on'
          - '/restart'
          
- id: '10000'
  alias: 'Telegram camera'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/cam'
  action:
  - service: script.notify_camera_n
    data_template:
      camera_number: "{{ trigger.event.data.args[0] }}"

- id: '10100'
  alias: 'Telegram lights OFF'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/lights_off'
  action:
  - service: light.turn_off
    entity_id: group.all_lights
    
- id: '10110'
  alias: 'Telegram lights ON'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/lights_on'
  action:
  - service: light.turn_on
    entity_id: group.all_lights
    
- id: '11030'
  alias: 'Toggle m5cam motion detection'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/toggle_camera.m5cam_motion_detection'
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.m5cam_motion_detection
  - service: notify.notify
    data_template:
      message: '{{ states.input_boolean.m5cam_motion_detection.state }}'

- id: '11040'
  alias: 'Toggle HiKam S5 (Soggiorno) motion detection'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      data: '/toggle_camera.hikam_s5_motion_detection'
  action:
  - service: input_boolean.toggle
    entity_id: input_boolean.soggiorno_motion_detection
  - service: notify.notify
    data_template:
      message: '{{ states.input_boolean.soggiorno_motion_detection.state }}'

- id: '12000'
  alias: 'Telegram restart home assistant'
  initial_state: 'on'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/restart'
  action:
  - service: homeassistant.restart

- id: '30000'
  alias: "M5StickC spegne lampada e lampadario"
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.m5stickc_pir_hat_button_a
    to: 'on'
  condition:
    condition: state
    entity_id: light.lampadario_soggiorno
    state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
      
- id: '30010'
  alias: "M5StickC accende lampada e lampadario"
  hide_entity: true
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.m5stickc_pir_hat_button_a
    to: 'on'
  condition:
    condition: state
    entity_id: light.lampadario_soggiorno
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
