homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config               # for filesize sensor
    - /tmp                  # for camera snapshots

# Enables the frontend
frontend:

# Enables configuration UI
config:

system_health:

#map:

http:
  
# Discover some devices automatically
discovery:
  ignore:
    - sonos
    - samsung_tv
    - harmony
    - deconz
    - roku
#  enable:
#    - homekit

ssdp:

zeroconf:

hacs:
  token: !secret hacs_github_token

shelly:
  discovery: true
  devices:
    - id: 32C429
      light_switch: true
      name: Soggiorno Shelly
      
sensor:
  - platform: fritzbox_netmonitor
  - platform: systemmonitor
    resources:
      - type: memory_free
      - type: processor_use
  - platform: uptime
    unit_of_measurement: hours
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    monitored_conditions:
      - temperature
  - platform: template
    sensors:
      mese_corrente:
        value_template: "{{ now().month }}"
        friendly_name: 'Mese corrente'
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  - platform: rpi_power
    text_state: true
  
remote:
  - platform: harmony
    host: 192.168.1.214
    name: Harmony Hub
    activity: Guarda TV

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

switch:
  - platform: command_line
    switches:
      camera_1_motion_detection: # zero.local
        command_on: "/usr/bin/curl http://192.168.1.24:7999/1/detection/start"
        command_off: "/usr/bin/curl http://192.168.1.24:7999/1/detection/pause"
        command_state: "/usr/bin/curl http://192.168.1.24:7999/1/detection/status"
        value_template: '{{ "ACTIVE" in value }}'
        friendly_name: Pi Zero W Motion Detection
      camera_2_motion_detection:
        command_on: "/usr/bin/curl http://localhost:7999/1/detection/start"
        command_off: "/usr/bin/curl http://localhost:7999/1/detection/pause"
        command_state: "/usr/bin/curl http://localhost:7999/1/detection/status"
        value_template: '{{ "ACTIVE" in value }}'
        friendly_name: HiKam S5 Motion Detection

input_boolean:
  camera_3_motion_detection:
    name: M5Cam Motion Detection
    initial: off

light:
  - name: "Soggiorno Lampadario"
    platform: mqtt
    state_topic: shellies/shelly1-32C429/relay/0
    command_topic: shellies/shelly1-32C429/relay/0/command
    payload_on: "on"
    payload_off: "off"
  - name: "Cucina Tavolo Lampadario"
    platform: mqtt
    state_topic: cucina-tavolo-lampadario/relay/0
    command_topic: cucina-tavolo-lampadario/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: cucina-tavolo-lampadario/status
    payload_available: 1
    payload_not_available: 0

camera:
  - platform: mjpeg     # camera1 setup with motion
    name: Pi Zero W
    mjpeg_url: http://192.168.1.24:8081
    still_image_url: http://192.168.1.24:8765/picture/1/current/
  - platform: mjpeg     # camera2 setup with motion
    name: HiKam S5
    mjpeg_url: http://localhost:8082
    still_image_url: http://localhost:8765/picture/2/current/

hue:
  bridges:
    - host: 192.168.1.85  
      allow_unreachable: false
      allow_hue_groups: false

tado:
  username: !secret tado_username
  password: !secret tado_password

device_tracker:
#  - platform: nmap_tracker
#    hosts:
#      - 192.168.1.210 # Ale
#      - 192.168.1.211 # Mari
  - platform: bluetooth_tracker
#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password
#    account_name: Alessandro
#    gps_accuracy_threshold: 100
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50

media_player:
  - platform: webostv
    host: 192.168.1.207
    turn_on_action:
      service: script.tv_on

recorder:
  purge_interval: 1
  purge_keep_days: 3
  exclude:
    domains:
      - camera
      - automation
      - weather
      - sensor
  include:
    entities:
      - sensor.home_assistant_v2_db
      - sensor.memory_free
      - sensor.processor_use
      - sensor.dark_sky_temperature
      - sensor.cameretta_temperature
      - sensor.cameretta_humidity
      - sensor.cucina_temperature
      - sensor.cucina_humidity
      - sensor.camera_da_letto_temperature
      - sensor.camera_da_letto_humidity
      - sensor.soggiorno_temperature
      - sensor.soggiorno_humidity
      - sensor.m5stickc_dht12_temperature
      - sensor.m5stickc_dht12_humidity
      - sensor.m5stickc_bmp280_temperature
      - sensor.m5stickc_bmp280_pressure
  
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

binary_sensor:
  - platform: ping
    host: 192.168.1.254
    count: 2
    scan_interval: 60

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_alex

notify:
  - platform: telegram
    chat_id: !secret telegram_chat_id_alex

# Example using a delay after start of Home Assistant
homekit:
  auto_start: False
  filter:
    exclude_domains:
      - sensor
      - automation
      - device_tracker

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
