homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config               # for filesize sensor
    - /tmp                  # for camera snapshots
  packages: !include_dir_named packages

frontend:

config:

system_health:

map:

http:

history:

logbook:

person:

ssdp:

zeroconf:

hacs:
  token: !secret hacs_github_token

api:

alexa:
  smart_home:
    filter:
      exclude_domains:
        - climate
        - automation
        - group
        - binary_sensor

shelly:
  discovery: true
  devices:
    - id: 32C429
      light_switch: true
      name: Soggiorno Shelly

sensor:
  - platform: fritzbox_netmonitor
    host: 192.168.1.254
  - platform: glances
    version: 3
    host: localhost
    resources:
      - 'disk_use_percent'
      - 'cpu_temp'
      - 'disk_free'
      - 'cpu_use_percent'
      - 'memory_free'
  - platform: uptime
    unit_of_measurement: hours
  - platform: template
    sensors:
      met_temperature:
        friendly_name: "Temperatura esterna"
        value_template: "{{ state_attr('weather.casa','temperature') }}"
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
        entity_id: weather.casa
      met_humidity:
        friendly_name: "Umidità esterna"
        value_template: "{{ state_attr('weather.casa','humidity') }}"
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
        entity_id: weather.casa
      met_pressure:
        friendly_name: "Pressione esterna"
        value_template: "{{ state_attr('weather.casa','pressure') }}"
        unit_of_measurement: 'hPa'
        icon_template: mdi:gauge
        entity_id: weather.casa
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
  - platform: rpi_power
    text_state: true
  
input_boolean:
  m5cam_motion_detection:
    name: M5Cam Motion Detection
    initial: off

light:
  - name: "Soggiorno Lampadario"
    platform: mqtt
    state_topic: shellies/shelly1-32C429/relay/0
    command_topic: shellies/shelly1-32C429/relay/0/command
    payload_on: "on"
    payload_off: "off"

camera:
  - platform: ffmpeg
    name: Xiaovv Q8
    input: rtsp://192.168.1.54/live/ch00_1      # 1980x1080
  - platform: ffmpeg
    name: HiKam S5
    input: rtsp://192.168.1.173/onvif1         # 1280x720

tado:
  username: !secret tado_username
  password: !secret tado_password

device_tracker:
  - platform: bluetooth_tracker
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50

smartir:

media_player:
  - platform: smartir
    name: LG smartir M5StickC PIR Hat
    device_code: 1001
    controller_data: m5stickc_pir/transmit_lg
  - platform: smartir
    name: LG smartir M5CameraF
    device_code: 1001
    controller_data: m5cameraf/transmit_lg
  - platform: webostv
    host: 192.168.1.207
    turn_on_action:
    - service: switch.turn_on
      entity_id: switch.m5stickc_pir_hat_lg_tv_power_on_2

recorder:
  purge_interval: 1
  purge_keep_days: 3
  exclude:
    domains:
      - camera
      - automation
      - weather
      - sensor
  include:
    domains:
      - person
    entities:
      - sensor.home_assistant_v2_db
      - sensor.0x00158d00018534af_action
      - sensor.glances_ram_free
      - sensor.glances_cpu_used
      - sensor.glances_cpu_temp
      - sensor.met_temperature
      - sensor.met_humidity
      - sensor.cameretta_temperature
      - sensor.cameretta_humidity
      - sensor.cucina_temperature
      - sensor.cucina_humidity
      - sensor.camera_da_letto_temperature
      - sensor.camera_da_letto_humidity
      - sensor.soggiorno_temperature
      - sensor.soggiorno_humidity
      - sensor.m5stickc_env_hat_dht12_temperature
      - sensor.m5stickc_env_hat_dht12_humidity
      - sensor.m5stickc_env_hat_bmp280_temperature
      - sensor.m5stickc_env_hat_bmp280_pressure

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_alex

notify:
  - platform: telegram
    chat_id: !secret telegram_chat_id_alex

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
