homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200
    - 172.30.33.0/24

sensor:
  - platform: uptime
  - platform: template
    sensors:
      met_temperature:
        friendly_name: "Temperatura esterna"
        value_template: "{{ state_attr('weather.casa','temperature') }}"
        unit_of_measurement: '°C'
        icon_template: mdi:thermometer
      met_humidity:
        friendly_name: "Umidità esterna"
        value_template: "{{ state_attr('weather.casa','humidity') }}"
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      met_pressure:
        friendly_name: "Pressione esterna"
        value_template: "{{ state_attr('weather.casa','pressure') }}"
        unit_of_measurement: 'hPa'
        icon_template: mdi:gauge

input_boolean:
  m5cam_motion_detection:
    name: M5Cam Motion Detection
    initial: off
  soggiorno_motion_detection:
    name: Soggiorno Motion Detection
    initial: off

camera:
#  - platform: ffmpeg
#    name: Xiaovv Q8
#    input: rtsp://192.168.1.54/live/ch00_1      # 1980x1080
  - platform: ffmpeg
    name: HiKam S5
    input: rtsp://192.168.1.173/onvif1         # 1280x720

device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: false
  - platform: tado
    username: !secret tado_username
    password: !secret tado_password
    home_id: !secret tado_home_id

recorder:
  purge_keep_days: 3
  exclude:
    domains:
      - camera
      - automation
      - weather

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
