decluttering_templates:
  barometro:
    card:
      entity: '[[entity]]'
      gauge:
        borders: false
        height: '[[size]]'
        highlights:
          - color: 'rgba(255, 255, 100, .50)'
            from: 1020
            to: 1040
          - color: 'rgba(100, 100, 255, .50)'
            from: 980
            to: 1000
        majorTicks:
          - 980
          - ☔
          - 1000
          - ⛅
          - 1020
          - ☼
          - 1040
        maxValue: 1040
        minValue: 980
        startAngle: 45
        strokeTicks: true
        ticksAngle: 270
        title: '[[name]]'
        type: radial-gauge
        units: hPa
        valueBox: true
        valueDec: 0
        width: '[[size]]'
      type: 'custom:canvas-gauge-card'
    default:
      - size: 180
      - name: Barometro
  igrometro:
    card:
      entity: '[[entity]]'
      gauge:
        borders: false
        height: '[[size]]'
        highlights:
          - color: 'rgba(50, 200, 50, .30)'
            from: 35
            to: 60
        majorTicks:
          - '20'
          - '30'
          - '40'
          - '50'
          - '60'
          - '70'
          - '80'
        maxValue: 80
        minValue: 20
        minorTicks: 2
        startAngle: 45
        strokeTicks: true
        ticksAngle: 270
        title: '[[name]]'
        type: radial-gauge
        units: '%'
        valueBox: true
        valueDec: 0
        valueInt: 2
        width: '[[size]]'
      type: 'custom:canvas-gauge-card'
    default:
      - size: 180
      - name: Igrometro
  termometro:
    card:
      entity: '[[entity]]'
      gauge:
        borders: false
        height: '[[height]]'
        highlights:
          - color: 'rgba(200, 50, 50, .15)'
            from: 25
            to: 35
          - color: 'rgba(50, 50, 200, .15)'
            from: 10
            to: 17
        majorTicks:
          - '10'
          - '15'
          - '20'
          - '25'
          - '30'
          - '35'
        maxValue: 35
        minValue: 10
        minorTicks: 10
        title: '[[name]]'
        type: linear-gauge
        valueBox: false
        width: '[[size]]'
      type: 'custom:canvas-gauge-card'
    default:
      - size: 100
      - height: 300
      - name: Termometro
resources:
  - type: module
    url: /community_plugin/monster-card/monster-card.js
  - type: module
    url: /community_plugin/canvas-gauge-card/canvas-gauge-card.js
  - type: module
    url: /community_plugin/decluttering-card/decluttering-card.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player.js
  - type: module
    url: /community_plugin/simple-weather-card/simple-weather-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card.js
title: Home Assistant
views:
  - badges: []
    cards:
      - entity: weather.casa
        name: ' '
        type: 'custom:simple-weather-card'
      - entities:
          - sensor.soggiorno_temperature
          - sensor.cucina_temperature
          - sensor.cameretta_temperature
          - sensor.camera_da_letto_temperature
        hour24: true
        show:
          fill: false
          icon: true
          labels: true
          name: true
        type: 'custom:mini-graph-card'
      - entity: media_player.lg_webos_smart_tv
        type: 'custom:mini-media-player'
      - cards:
          - camera_image: camera.hikam_s5
            entities:
              - sensor.soggiorno_temperature
              - sensor.soggiorno_humidity
            title: Soggiorno
            type: picture-glance
          - cards:
              - camera_image: camera.m5cam
                entities:
                  - sensor.soggiorno_temperature
                  - sensor.soggiorno_humidity
                title: Soggiorno
                type: picture-glance
              - camera_image: camera.pi_zero_w
                entities:
                  - sensor.camera_da_letto_temperature
                  - sensor.camera_da_letto_humidity
                  - light.camera_lampadario
                title: Camera
                type: picture-glance
            type: horizontal-stack
        type: vertical-stack
      - entities:
          - entity: sensor.uptime
          - entity: sensor.memory_free
          - entity: sensor.processor_use
          - entity: sensor.home_assistant_v2_db
          - entity: sensor.rpi_power_status
        title: Sistema
        type: glance
      - card:
          title: Luci accese
          type: entities
        filter:
          include:
            - domain: light
              state: 'on'
        show_empty: false
        type: 'custom:monster-card'
      - card:
          card:
            title: Persone in casa
            type: glance
          entities:
            - entity: group.alex
            - entity: group.mari
          state_filter:
            - home
          type: entity-filter
        conditions:
          - entity: group.people
            state: home
        type: conditional
      - entities:
          - entity: group.all_lights
        type: entities
    path: default_view
    title: Home
  - badges: []
    cards:
      - entity: media_player.lg_webos_smart_tv
        type: media-control
      - card:
          show_header_toggle: true
          title: Luci
          type: entities
        filter:
          include:
            - entity_id: light.*
        type: 'custom:monster-card'
      - card:
          show_header_toggle: true
          title: Interruttori
          type: entities
        filter:
          exclude:
            - entity_id: '*restart'
            - entity_id: '*led'
            - entity_id: '*motion_detection'
          include:
            - domain: switch
        type: 'custom:monster-card'
      - entities:
          - entity: remote.harmony_hub
        show_header_toggle: false
        title: Telecomandi
        type: entities
      - entities:
          - script.tv_off
          - script.tv_on
        show_header_toggle: false
        theme: default
        title: Script
        type: entities
    path: main
    title: Casa
  - badges: []
    cards:
      - entities:
          - entity: group.people
          - entity: group.alex
          - entity: group.mari
          - entity: group.all_devices
        show_header_toggle: false
        theme: default
        title: Presenza
        type: entities
      - entities:
          - entity: device_tracker.iphone_di_alessandro
          - entity: device_tracker.iphone_di_alessandro_2
        show_header_toggle: false
        title: Alessandro
        type: entities
      - entities:
          - entity: device_tracker.iphone_di_mariangela
          - entity: device_tracker.iphone_di_mariangela_2
        show_header_toggle: false
        title: Mariangela
        type: entities
      - card:
          title: Motion Detection
          type: entities
        filter:
          include:
            - entity_id: switch.*motion*
            - entity_id: input_boolean.*motion*
        type: 'custom:monster-card'
      - entities:
          - entity: binary_sensor.m5cam_pir
            secondary_info: last-changed
        type: entities
    icon: 'mdi:account-multiple'
    path: people
    title: Persone
  - badges: []
    cards:
      - cards:
          - cards:
              - entities:
                  - sensor.met_temperature
                  - sensor.m5stickc_env_hat_dht12_temperature
                  - sensor.m5stickc_env_hat_bmp280_temperature
                hour24: true
                show:
                  fill: false
                  icon: true
                  labels: true
                  name: false
                  state: true
                type: 'custom:mini-graph-card'
              - cards:
                  - template: termometro
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: sensor.met_temperature
                  - template: termometro
                    type: 'custom:decluttering-card'
                    variables:
                      - entity: sensor.m5stickc_env_hat_bmp280_temperature
                type: horizontal-stack
            type: horizontal-stack
          - cards:
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_dht12_humidity
              - template: barometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_bmp280_pressure
            type: horizontal-stack
        title: ⛅ Outdoor
        type: 'custom:vertical-stack-in-card'
      - cards:
          - cards:
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.cucina_temperature
                  - name: Cucina
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.soggiorno_temperature
                  - name: Soggiorno
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.cameretta_temperature
                  - name: Cameretta
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.camera_da_letto_temperature
                  - name: Camera da letto
            type: horizontal-stack
          - cards:
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.cucina_humidity
                  - name: Cucina
                  - size: 100
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.soggiorno_humidity
                  - name: Soggiorno
                  - size: 100
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.cameretta_humidity
                  - name: Cameretta
                  - size: 100
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.camera_da_letto_humidity
                  - name: Camera da letto
                  - size: 100
            type: horizontal-stack
          - entities:
              - sensor.cucina_temperature
              - sensor.soggiorno_temperature
              - sensor.cameretta_temperature
              - sensor.camera_da_letto_temperature
            hour24: true
            show:
              fill: false
              icon: true
              labels: true
              name: true
              state: true
            type: 'custom:mini-graph-card'
        title: "\U0001F3E0 Indoor"
        type: 'custom:vertical-stack-in-card'
      - cards:
          - card:
              show_header_toggle: false
              title: Riscaldamento
              type: entities
            filter:
              include:
                - domain: climate
            type: 'custom:monster-card'
          - card:
              show_header_toggle: false
              title: Temperature
              type: entities
            filter:
              include:
                - entity_id: sensor.*temperature
            type: 'custom:monster-card'
        type: vertical-stack
    path: climate
    title: Climatizzazione
  - badges: []
    cards:
      - card:
          title: Automazioni
          type: entities
        filter:
          include:
            - domain: automation
        type: 'custom:monster-card'
    path: automation
    title: Automazioni
  - badges: []
    cards:
      - card:
          title: Motion Detection
          type: entities
        filter:
          include:
            - entity_id: switch.*motion*
            - entity_id: input_boolean.*motion*
        type: 'custom:monster-card'
      - camera_image: camera.hikam_s5
        camera_view: live
        entities:
          - sensor.soggiorno_temperature
          - sensor.soggiorno_humidity
          - light.soggiorno_lampada
          - switch.camera_2_motion_detection
        title: Soggiorno
        type: picture-glance
      - camera_image: camera.pi_zero_w
        camera_view: live
        entities:
          - sensor.camera_da_letto_temperature
          - sensor.camera_da_letto_humidity
          - light.camera_lampadario
          - switch.camera_1_motion_detection
        title: Camera da letto
        type: picture-glance
      - camera_image: camera.m5cam
        camera_view: live
        entities:
          - sensor.soggiorno_temperature
          - sensor.soggiorno_humidity
          - light.soggiorno_lampada
          - switch.camera_2_motion_detection
        title: Soggiorno
        type: picture-glance
      - card:
          show_header_toggle: false
          title: LG TV
          type: entities
        filter:
          include:
            - entity_id: '*lg*'
        type: 'custom:monster-card'
      - camera_image: camera.m5cameraf
        camera_view: live
        entities:
          - sensor.soggiorno_temperature
          - sensor.soggiorno_humidity
        title: M5CameraF
        type: picture-glance
    icon: 'mdi:cctv'
    theme: default
    title: Videosorveglianza
  - badges: []
    cards:
      - card:
          show_header_toggle: false
          title: M5CameraF
          type: entities
        filter:
          include:
            - entity_id: '*m5cameraf*'
        type: 'custom:monster-card'
      - cards:
          - cards:
              - template: igrometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_dht12_humidity
                  - name: Umidità
              - template: barometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_bmp280_pressure
                  - name: Pressione
            type: horizontal-stack
          - cards:
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_bmp280_temperature
                  - name: Temperatura (BMP280)
                  - size: 140
                  - height: 300
              - template: termometro
                type: 'custom:decluttering-card'
                variables:
                  - entity: sensor.m5stickc_env_hat_dht12_temperature
                  - name: Temperatura (DHT12)
                  - size: 140
                  - height: 300
            type: horizontal-stack
          - entities:
              - sensor.m5stickc_env_hat_bmp280_temperature
              - sensor.m5stickc_env_hat_dht12_temperature
              - entity: sensor.m5stickc_env_hat_dht12_humidity
                y_axis: secondary
            hour24: true
            show:
              fill: false
              icon: true
              labels: true
              name: true
              state: true
            type: 'custom:mini-graph-card'
        title: M5StickC ENV Unit
        type: 'custom:vertical-stack-in-card'
      - card:
          show_header_toggle: false
          title: M5StickC PIR Hat
          type: entities
        filter:
          include:
            - entity_id: '*m5stickc_pir*'
        type: 'custom:monster-card'
      - card:
          show_header_toggle: false
          title: M5Cam
          type: entities
        filter:
          include:
            - entity_id: '*m5cam'
            - entity_id: '*m5cam_*'
        type: 'custom:monster-card'
      - card:
          show_header_toggle: false
          title: M5StickC ENV Hat
          type: entities
        filter:
          include:
            - entity_id: '*m5stickc_env*'
        type: 'custom:monster-card'
    icon: 'mdi:wrench'
    title: Lab
  - badges: []
    cards:
      - entities:
          - entity: sensor.uptime
          - entity: sensor.memory_free
          - entity: sensor.processor_use
          - entity: sensor.rpi_power_status
        title: System
        type: glance
      - entities:
          - entity: binary_sensor.ping_binary_sensor
          - entity: sensor.fritz_netmonitor
        title: Network
        type: glance
      - entities:
          - entity: sensor.disk_free
          - entity: sensor.disk_use_percent
          - entity: sensor.home_assistant_v2_db
        title: Storage
        type: glance
    icon: 'mdi:server-network'
    title: System
