substitutions:
  devicename: m5atom_ir
  upper_devicename: M5Atom IR
  mqtt_broker: 192.168.1.200

esphome:
  name: $devicename
  platform: ESP32
  board: pico32
  platformio_options:
    upload_speed: 115200

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: ${upper_devicename} Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button
    on_press:
      then:
        - light.toggle: led1
        - switch.toggle: ir1

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} Restart
  - platform: template
    name: ${upper_devicename} LG TV Power On
    id: ir1
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF23DC              # = 551494620
          nbits: 32
          transmitter_id: internal

mqtt:
  broker: ${mqtt_broker}
  discovery: false
  on_json_message:
    topic: ${devicename}/transmit_lg        # Examples of json payload : { "data": 551494620, "nbits": 32 }
    then:                                   #                            { "data": 551494620 }
      - remote_transmitter.transmit_lg:
          transmitter_id: internal
          data: !lambda |-
            uint32_t data = 0;
            if (x.containsKey("data"))
              data = x["data"];
            return data;
          nbits: !lambda |-
            uint8_t nbits = 32;
            if (x.containsKey("nbits"))
              nbits = x["nbits"];
            return nbits;

# Grove IR Receiver
remote_receiver:
  pin:
    number: GPIO26
    inverted: true
  dump: all

# Grove IR Transmitter
remote_transmitter:
  - pin:
      number: GPIO32
    carrier_duty_percent: 50%
    id: grove
# M5Atom internal IR Transmitter
  - pin:
      number: GPIO12
    carrier_duty_percent: 50%
    id: internal

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO27
    num_leds: 25
    name: ${upper_devicename} Led Matrix
    id: led1
    effects:
      - addressable_rainbow:
      - random:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      
