substitutions:
  devicename: m5atom_env
  upper_devicename: M5Atom ENV
  mqtt_broker: 192.168.1.200

esphome:
  name: $devicename
  platform: ESP32
  board: pico32
  platformio_options:
    upload_speed: 115200

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

logger:

api:

ota:

web_server:

#mqtt:
#  broker: ${mqtt_broker}

i2c:
  - id: grove_bus
    sda: GPIO26
    scl: GPIO32
    scan: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button
    on_press:
      then:
        - light.toggle: led1

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime
# ENV Unit
  - platform: bmp280
    i2c_id: grove_bus
    temperature:
      name: ${upper_devicename} BMP280 Temperature
      id: temp1
      on_value:
        - light.turn_on:
            id: led1
            red: !lambda "return x - 21.0;"
            green: !lambda "return 0.5;"
            blue: !lambda "return 20.0 - x;"
    pressure:
      name: ${upper_devicename} BMP280 Pressure
    address: 0x76
    update_interval: 5s
  - platform: dht12
    i2c_id: grove_bus
    temperature:
      name: ${upper_devicename} DHT12 Temperature
      id: temp2
    humidity:
      name: ${upper_devicename} DHT12 Humidity

switch:
  - platform: restart
    name: ${upper_devicename} Restart

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO27
    num_leds: 25
    name: ${upper_devicename} Led Matrix
    id: led1
    effects:
      - addressable_rainbow:
      - random:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
