substitutions:
  devicename: m5stickc_pir
  upper_devicename: M5StickC PIR Hat

esphome:
  name: $devicename
  platform: ESP32
  board: m5stick-c
  on_boot:
    priority: -100
    then:
      - switch.turn_on: led1
      
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: $devicename Fallback Hotspot
    password: !secret wifi_password

captive_portal:

logger:

api:

ota:

web_server:

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - switch.turn_on: led1
    on_release:
      then:
        - switch.turn_off: led1
        
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - switch.turn_on: led1
    on_release:
      then:
        - switch.turn_off: led1
        
  - platform: gpio
    id: motion1
    pin:
      number: GPIO36
    name: ${upper_devicename} PIR
    device_class: motion
    on_press:
      then:
        - switch.turn_on: led1
        
  - platform: template
    id: timed_light
    lambda: |-
      static int fresh_boot = 1;
      if (fresh_boot) {
        fresh_boot = 0;
        return true;
      } else {
        return id(motion1).state;
      }
    filters:
      - delayed_off: 5s
    on_release:
      then:
        - switch.turn_off: led1

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

#interval:
#  - interval: 12h
#    then:
#      - switch.turn_on: restart1

switch:

  - platform: restart
    name: ${upper_devicename} Restart
    id: restart1
    
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: ${upper_devicename} Led
    id: led1
