substitutions:
  devicename: m5stickc_pir
  upper_devicename: M5StickC PIR Hat

esphome:
  name: $devicename
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

mqtt:
  broker: 192.168.1.200
  discovery: false
  on_json_message:
    topic: ${devicename}/transmit_lg        # Examples of json payload : { "data": 551494620, "nbits": 32 }
    then:                                   #                            { "data": 551494620 }
      - remote_transmitter.transmit_lg:
          transmitter_id: grove
          data: !lambda |-
            uint32_t data = 0;
            if (x.containsKey("data"))
              data = x["data"];
            return data;
          nbits: !lambda |-
            uint8_t nbits = 32;
            if (x.containsKey("nbits"))
              nbits = x["nbits"];
            return nbits;
      - remote_transmitter.transmit_lg:
          transmitter_id: internal
          data: !lambda |-
            uint32_t data = 0;
            if (x.containsKey("data"))
              data = x["data"];
            return data;
          nbits: !lambda |-
            uint8_t nbits = 32;
            if (x.containsKey("nbits"))
              nbits = x["nbits"];
            return nbits;

# Grove IR Receiver
remote_receiver:
  pin:
    number: GPIO33
    inverted: true
  dump: all

# Grove IR Transmitter
remote_transmitter:
  - pin:
      number: GPIO32
    carrier_duty_percent: 50%
    id: grove
# M5StickC internal IR Transmitter
  - pin:
      number: GPIO9
    carrier_duty_percent: 50%
    id: internal

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - switch.turn_on: led1
    on_release:
      then:
        - switch.turn_off: led1
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - switch.turn_on: led1
    on_release:
      then:
        - switch.turn_off: led1
  - platform: gpio
    pin:
      number: GPIO36
    name: ${upper_devicename} PIR
    device_class: motion

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} Restart
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: ${upper_devicename} Led
    id: led1
  - platform: template
    name: ${upper_devicename} LG TV Power on
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF23DC              # = 551494620
          nbits: 32
          transmitter_id: grove
