substitutions:
  devicename: m5stickc_pir
  upper_devicename: M5StickC PIR Hat

esphome:
  name: $devicename
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

# Grove IR Receiver
remote_receiver:
  pin:
    number: GPIO33
    inverted: true
  dump: all

# Grove IR Transmitter
#remote_transmitter:
#  pin:
#    number: GPIO32
#  carrier_duty_percent: 50%

# M5StickC IR Transmitter
remote_transmitter:
  pin:
    number: GPIO9
  carrier_duty_percent: 50%

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: ${upper_devicename} Button A
    on_press:
      then:
        - switch.toggle: led1
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: ${upper_devicename} Button B
    on_press:
      then:
        - switch.toggle: led1
  - platform: gpio
    pin:
      number: GPIO36
    name: ${upper_devicename} PIR
    device_class: motion

sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} Restart
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    name: ${upper_devicename} Led
    id: led1
  - platform: template
    name: ${upper_devicename} LG Power on
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF23DC
          nbits: 32
  - platform: template
    name: ${upper_devicename} LG Power off
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DFA35C
          nbits: 32
  - platform: template
    name: ${upper_devicename} LG Standby
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DFD728
          nbits: 32
  - platform: template
    name: ${upper_devicename} LG Mute
    turn_on_action:
      - remote_transmitter.transmit_lg:
          data: 0x20DF906F
          nbits: 32
