substitutions:
  devicename: smartusb
  upper_devicename: Smart USB

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

#web_server:
#  port: 80
  
sensor:
  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
  - platform: uptime
    name: ${upper_devicename} Uptime

switch:
  - platform: restart
    name: ${upper_devicename} Restart
  - platform: gpio
    name: ${upper_devicename} Relay
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

#text_sensor:
#  - platform: version
#    name: ${upper_devicename} ESPHome Version

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${upper_devicename} Button
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
