homekit:
  auto_start: false
  filter:
    include_domains:
      - light
      - climate
      - media_player

automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:02  # Waits 2 minutes
      - service: homekit.start
