homeassistant:
  customize:
    media_player.lg_webos_smart_tv:
      device_class: tv
    media_player.skyq_soggiorno:
      device_class: tv
    media_player.universal_remote:
      device_class: tv

remote:
  - platform: harmony
    name: Soggiorno
    host: 192.168.1.214

input_boolean:
  stereo_state:
  
media_player:

  - platform: skyq
    name: SkyQ Soggiorno
    host: 192.168.1.27
    room: soggiorno
    config_directory: '/config/'
    generate_switches_for_channels: false
    sources:
      SkyArte: '1,2,0'
      SkyCinema1: '3,0,1'
      Rai1: '5,5,0,1'
      Rai2: '5,5,0,2'
      Rai3: '5,5,0,3'
      La7: '5,5,0,7'

  - platform: webostv
    host: 192.168.1.207
    turn_on_action:
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: LG TV

  - platform: universal
    name: Universal Remote
    children:
      - media_player.lg_webos_smart_tv
      - media_player.skyq_soggiorno
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.lg_webos_smart_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.lg_webos_smart_tv
          volume_level: '{{ volume_level }}'
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.skyq_soggiorno
          source: '{{ source }}'
    attributes:
      is_volume_muted: media_player.lg_webos_smart_tv|is_volume_muted
      volume_level: media_player.lg_webos_smart_tv|volume_level
      source_list: media_player.skyq_soggiorno|source_list

  - platform: universal
    name: Stereo
    commands:
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.turn_on_stereo
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.turn_off_stereo
    attributes:
      state: input_boolean.stereo_state

switch:
  - platform: template
    switches:
      tv:
        friendly_name: TV
        value_template: "{{ is_state_attr('media_player.lg_webos_smart_tv', 'source', 'HDMI1') }}"
        turn_on:
          - service: media_player.turn_on
            data:
              entity_id: media_player.lg_webos_smart_tv
          - service: media_player.select_source
            data:
              entity_id: media_player.lg_webos_smart_tv
              source: HDMI1
        turn_off:
          - service: media_player.turn_off
            data:
              entity_id: media_player.lg_webos_smart_tv

script:

  skyarte:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: media_player.turn_on
        data:
          entity_id: media_player.skyq_soggiorno
      - service: media_player.select_source
        data:
          entity_id: media_player.skyq_soggiorno
          source: SkyArte
  la7:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: media_player.turn_on
        data:
          entity_id: media_player.skyq_soggiorno
      - service: media_player.select_source
        data:
          entity_id: media_player.skyq_soggiorno
          source: La7
  rai1:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: media_player.turn_on
        data:
          entity_id: media_player.skyq_soggiorno
      - service: media_player.select_source
        data:
          entity_id: media_player.skyq_soggiorno
          source: Rai1
  rai2:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: media_player.turn_on
        data:
          entity_id: media_player.skyq_soggiorno
      - service: media_player.select_source
        data:
          entity_id: media_player.skyq_soggiorno
          source: Rai2
  rai3:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: media_player.turn_on
        data:
          entity_id: media_player.skyq_soggiorno
      - service: media_player.select_source
        data:
          entity_id: media_player.skyq_soggiorno
          source: Rai3

  turn_on_stereo:
    alias: "Accendi Stereo"
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: Pioneer Ricevitore AV

  turn_off_stereo:
    alias: "Spegni Stereo"
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOff
          device: Pioneer Ricevitore AV
