homeassistant:
  customize:
    media_player.lg_webos_smart_tv:
      device_class: tv

remote:
  - platform: harmony
    name: Soggiorno
    host: 192.168.1.214

input_boolean:
  stereo_state:

webostv:
  host: 192.168.1.207
  name: TV
  turn_on_action:
    - service: remote.send_command
      data:
        entity_id: remote.soggiorno
        command:
          - PowerOn
        device: LG TV
  
media_player:

  - platform: universal
    name: Stereo
    commands:
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.turn_on_stereo
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.turn_off_stereo
    attributes:
      state: input_boolean.stereo_state

script:

  turn_on_tv:
    alias: "Accendi TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: LG TV

  turn_off_tv:
    alias: "Spegni TV"
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOff
          device: LG TV

  turn_on_stereo:
    alias: "Accendi Stereo"
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: Pioneer Ricevitore AV
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - InputCd
          device: Pioneer Ricevitore AV

  turn_off_stereo:
    alias: "Spegni Stereo"
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOff
          device: Pioneer Ricevitore AV
