homeassistant:
  customize:
    media_player.lg_webos_smart_tv:
      device_class: tv
    media_player.universal_remote:
      device_class: tv

remote:
  - platform: harmony
    name: Soggiorno
    host: 192.168.1.214

smartir:

input_select:
  elenco_canali:
    name: Elenco canali
    options:
      - '1 Rai1'
      - '2 Rai2'
      - '3 Rai3'
      - '7 La7'
    initial: 7 La7
    icon: mdi:television

input_boolean:
  stereo_state:
  
media_player:

  - platform: webostv
    host: 192.168.1.207
    turn_on_action:
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: LG TV

  - platform: universal
    name: Universal Remote
    children:
      - media_player.lg_webos_smart_tv
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.lg_webos_smart_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.lg_webos_smart_tv
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.lg_webos_smart_tv
          volume_level: '{{ volume_level }}'
      select_source:
          service: script.turn_on
          data_template:
            entity_id: >
              {% if   source == '1 Rai1' %}
                script.rai1
              {% elif source == '2 Rai2' %}
                script.rai2
              {% elif source == '3 Rai3' %}
                script.rai3
              {% elif source == '7 La7' %}
                script.la7
              {% else %} 
                script.sky_off
              {% endif %}
    attributes:
      is_volume_muted: media_player.lg_webos_smart_tv|is_volume_muted
      volume_level: media_player.lg_webos_smart_tv|volume_level
      source_list: input_select.elenco_canali|options

  - platform: universal
    name: Stereo
    commands:
      turn_on:
        service: script.turn_on
        data:
          entity_id: script.turn_on_stereo
      turn_off:
        service: script.turn_on
        data:
          entity_id: script.turn_off_stereo
    attributes:
      state: input_boolean.stereo_state

sensor:
  - platform: rest
    resource: http://192.168.1.27:9006/as/system/information/
    name: SkyQ
    json_attributes:
        - systemUptime
        - activeStandby
    value_template: "{{ value_json.systemUptime }}"
    unit_of_measurement: 's'
    scan_interval: 5

binary_sensor:
  - platform: template
    sensors:
      skyqpower:
        value_template: "{{ is_state_attr('sensor.skyq', 'activeStandby', false) }}"
        friendly_name: SkyQ Power
        device_class: moving

switch:
  - platform: template
    switches:
      tv:
        friendly_name: TV
        value_template: "{{ is_state_attr('media_player.lg_webos_smart_tv', 'source', 'HDMI1') }}"
        turn_on:
          - service: media_player.turn_on
            data:
              entity_id: media_player.lg_webos_smart_tv
          - service: media_player.select_source
            data:
              entity_id: media_player.lg_webos_smart_tv
              source: HDMI1
        turn_off:
        - service: media_player.turn_off
          data:
            entity_id: media_player.lg_webos_smart_tv
      sky:
        friendly_name: Sky
        value_template: "{{ is_state_attr('sensor.skyq', 'activeStandby', false) }}"
        turn_on:
          service: script.turn_on
          data:
            entity_id: script.sky_on
        turn_off:
          service: script.turn_on
          data:
            entity_id: script.sky_off

script:
  sky_on:
    alias: Accendi Sky
    sequence:
      - condition: template
        value_template: "{{ not is_state_attr('sensor.skyq', 'activeStandby', false) }}"
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerToggle
          device: Sky DVR
  sky_off:
    alias: Spegni Sky
    sequence:
      - condition: template
        value_template: "{{ is_state_attr('sensor.skyq', 'activeStandby', false) }}"
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerToggle
          device: Sky DVR
  la7:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.sky
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - "Return"
            - "5"
            - "5"
            - "0"
            - "7"
          device: Sky DVR
          delay_secs: 0.5
  rai1:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: switch.turn_on
        data:
          entity_id: switch.sky
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - "Return"
            - "5"
            - "5"
            - "0"
            - "1"
          device: Sky DVR
          delay_secs: 0.5
  rai2:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: switch.turn_on
        data:
          entity_id: switch.sky
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - "Return"
            - "5"
            - "5"
            - "0"
            - "2"
          device: Sky DVR
          delay_secs: 0.5
  rai3:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tv
      - service: switch.turn_on
        data:
          entity_id: switch.sky
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - "Return"
            - "5"
            - "5"
            - "0"
            - "3"
          device: Sky DVR
          delay_secs: 0.5

  turn_on_stereo:
    alias: "Accendi Stereo"
    sequence:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOn
          device: Pioneer Ricevitore AV

  turn_off_stereo:
    alias: "Spegni Stereo"
    sequence:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.stereo_state
      - service: remote.send_command
        data:
          entity_id: remote.soggiorno
          command:
            - PowerOff
          device: Pioneer Ricevitore AV
      
