telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id_alex

notify:
  - platform: telegram
    name: Alessandro
    chat_id: !secret telegram_chat_id_alex

automation:
  - id: '1628671286056'
    alias: Apri il cancello da telegram
    description: ''
    use_blueprint:
      path: marc-romu/telegram-bot-respond-to-telegram-command-by-executing-an-action.yaml
      input:
        telegram_command: /open
        sequence:
        - service: notify.alessandro
          data:
            message: Cancello aperto
            data:
              keyboard:
              - /open
